/* ═══════════════════════════════════════════════════════════════
   lang-data.js — the languages, and the phrase book

   The OS was written in English, and every string in it is a literal
   sitting in the middle of the code that draws it. Rather than tear
   twelve thousand lines apart to hang a key on each one, the English
   string *is* the key: this file maps the phrases the interface
   actually shows onto their translations, and i18n.js swaps them in
   the DOM as they appear.

   That has one consequence worth stating plainly: coverage is
   partial by design. A phrase missing from this book stays English,
   the Language pane reports honestly how much is covered, and you
   can fill in the rest yourself without touching a file.
   ═══════════════════════════════════════════════════════════════ */
window.DS = window.DS || {};

(function (DS) {
  "use strict";

  /* locale = what Intl is handed for dates and numbers.
     rtl    = the script runs right to left. */
  DS.LANGS = [
    { id: "en", name: "English",  native: "English",  locale: "en",    rtl: false },
    { id: "es", name: "Spanish",  native: "Español",  locale: "es",    rtl: false },
    { id: "fr", name: "French",   native: "Français", locale: "fr",    rtl: false },
    { id: "de", name: "German",   native: "Deutsch",  locale: "de",    rtl: false },
    { id: "hi", name: "Hindi",    native: "हिन्दी",     locale: "hi-IN", rtl: false },
    { id: "ja", name: "Japanese", native: "日本語",    locale: "ja-JP", rtl: false },
    { id: "ar", name: "Arabic",   native: "العربية",   locale: "ar",    rtl: true  }
  ];

  /* ── the phrase book ──────────────────────────────────────────
     English key → translation. Keys match exactly, after a trim and
     after any trailing "…", ":" or "?" is set aside and re-attached,
     so "Settings" and "Settings…" both resolve from one entry. */
  DS.PHRASES = {

    es: {
      "About This System": "Acerca de este sistema",
      "System Settings": "Ajustes del sistema",
      "Tune the Glass": "Ajustar el cristal",
      "Open Terminal": "Abrir el terminal",
      "Close All Windows": "Cerrar todas las ventanas",
      "Restart": "Reiniciar",
      "Language": "Idioma",
      "View": "Ver",
      "Help": "Ayuda",
      "Theme": "Tema",
      "Minimise": "Minimizar",
      "Maximise": "Maximizar",
      "Restore": "Restaurar",
      "Close Window": "Cerrar la ventana",
      "No window open": "Ninguna ventana abierta",
      "Take the guided tour": "Hacer el recorrido guiado",
      "Show me the glass": "Muéstrame el cristal",
      "Keyboard": "Teclado",
      "Launcher": "Lanzador",
      "Cycle windows": "Cambiar de ventana",
      "Close window": "Cerrar la ventana",
      "Minimise window": "Minimizar la ventana",
      "Settings": "Ajustes",
      "Lock the screen": "Bloquear la pantalla",
      "Finder": "Buscador",
      "Notes": "Notas",
      "Terminal": "Terminal",
      "Calculator": "Calculadora",
      "Clock": "Reloj",
      "Calendar": "Calendario",
      "Focus": "Concentración",
      "Music": "Música",
      "Photos": "Fotos",
      "Image Lab": "Laboratorio de imagen",
      "Audio Lab": "Laboratorio de audio",
      "Video Lab": "Laboratorio de vídeo",
      "Search": "Buscar",
      "Glass Forge": "Forja de cristal",
      "About": "Acerca de",
      "Bug Reporter": "Informe de errores",
      "Cancel": "Cancelar",
      "OK": "Aceptar",
      "Delete": "Eliminar",
      "Create": "Crear",
      "Got it": "Entendido",
      "Save": "Guardar",
      "Open": "Abrir",
      "Close": "Cerrar",
      "Remove": "Quitar",
      "Add": "Añadir",
      "Apply": "Aplicar",
      "Reset": "Restablecer",
      "Done": "Hecho",
      "On": "Activado",
      "Off": "Desactivado",
      "Full": "Completo",
      "Reduced": "Reducido",
      "Small": "Pequeño",
      "Medium": "Mediano",
      "Large": "Grande",
      "Bottom": "Abajo",
      "Left": "Izquierda",
      "Right": "Derecha",
      "Position": "Posición",
      "Size": "Tamaño",
      "Behaviour": "Comportamiento",
      "Preview": "Vista previa",
      "Title": "Título",
      "Severity": "Gravedad",
      "Copy": "Copiar",
      "Appearance": "Apariencia",
      "Glass": "Cristal",
      "Desktop": "Escritorio",
      "Storage": "Almacenamiento",
      "Wallpaper": "Fondo",
      "Looks": "Estilos",
      "Users": "Usuarios",
      "Widgets": "Widgets",
      "Shortcuts": "Atajos",
      "Lock": "Bloqueo",
      "Zoom": "Zoom",
      "Presets": "Preajustes",
      "Optics": "Óptica",
      "Blur": "Desenfoque",
      "Tint": "Tono",
      "Saturation": "Saturación",
      "Brightness": "Brillo",
      "Edge thickness": "Grosor del borde",
      "Dispersion": "Dispersión",
      "Sheen": "Brillo especular",
      "Corner radius": "Radio de las esquinas",
      "Surface finish": "Acabado de la superficie",
      "The light": "La luz",
      "Refraction": "Refracción",
      "Motion": "Movimiento",
      "Reset optics": "Restablecer la óptica",
      "Account": "Cuenta",
      "User name": "Nombre de usuario",
      "Windows": "Ventanas",
      "Dock": "Dock",
      "Icon size": "Tamaño de los iconos",
      "Magnification": "Ampliación",
      "Auto-hide": "Ocultar automáticamente",
      "Setup": "Configuración inicial",
      "Apps in the dock": "Apps en el dock",
      "Bring to front": "Traer al frente",
      "Remove from dock": "Quitar del dock",
      "Customise the dock": "Personalizar el dock",
      "Add to the dock": "Añadir al dock",
      "All dock settings": "Todos los ajustes del dock",
      "New Folder": "Nueva carpeta",
      "New Note": "Nueva nota",
      "Import files": "Importar archivos",
      "Add widget": "Añadir widget",
      "Remove widget": "Quitar widget",
      "Show in Finder": "Mostrar en el Buscador",
      "Wallpaper studio": "Estudio de fondos",
      "Applications": "Aplicaciones",
      "Files": "Archivos",
      "Actions": "Acciones",
      "Application": "Aplicación",
      "System zoom": "Zoom del sistema",
      "Window zoom": "Zoom de la ventana",
      "Zoom in": "Acercar",
      "Zoom out": "Alejar",
      "Actual size": "Tamaño real",
      "Reset zoom": "Restablecer el zoom",
      "Interface language": "Idioma de la interfaz",
      "Region and formats": "Región y formatos",
      "24-hour clock": "Reloj de 24 horas",
      "First day of the week": "Primer día de la semana",
      "Right-to-left layout": "Diseño de derecha a izquierda",
      "Sunday": "Domingo",
      "Monday": "Lunes",
      "Automatic": "Automático",
      "Coverage": "Cobertura",
      "Report a bug": "Informar de un error",
      "Bug reports": "Informes de errores",
      "What happened?": "¿Qué ha pasado?",
      "Steps to reproduce": "Pasos para reproducirlo",
      "Include diagnostics": "Incluir diagnósticos",
      "File the report": "Enviar el informe",
      "Filed reports": "Informes enviados",
      "No reports yet": "Todavía no hay informes",
      "Copy as Markdown": "Copiar como Markdown",
      "Diagnostics": "Diagnósticos",
      "Cosmetic": "Estético",
      "Annoying": "Molesto",
      "Broken": "Roto",
      "Hide the bug": "Ocultar el bicho",
      "Begin": "Comenzar",
      "Continue": "Continuar",
      "Back": "Atrás",
      "Skip setup": "Omitir la configuración",
      "Who is using this?": "¿Quién va a usarlo?",
      "Squash it": "Aplástalo"
    },

    fr: {
      "About This System": "À propos de ce système",
      "System Settings": "Réglages du système",
      "Tune the Glass": "Régler le verre",
      "Open Terminal": "Ouvrir le terminal",
      "Close All Windows": "Fermer toutes les fenêtres",
      "Restart": "Redémarrer",
      "Language": "Langue",
      "View": "Affichage",
      "Help": "Aide",
      "Theme": "Thème",
      "Minimise": "Réduire",
      "Maximise": "Agrandir",
      "Restore": "Restaurer",
      "Close Window": "Fermer la fenêtre",
      "No window open": "Aucune fenêtre ouverte",
      "Take the guided tour": "Suivre la visite guidée",
      "Show me the glass": "Montrez-moi le verre",
      "Keyboard": "Clavier",
      "Launcher": "Lanceur",
      "Cycle windows": "Changer de fenêtre",
      "Close window": "Fermer la fenêtre",
      "Minimise window": "Réduire la fenêtre",
      "Settings": "Réglages",
      "Lock the screen": "Verrouiller l'écran",
      "Finder": "Finder",
      "Notes": "Notes",
      "Terminal": "Terminal",
      "Calculator": "Calculatrice",
      "Clock": "Horloge",
      "Calendar": "Calendrier",
      "Focus": "Concentration",
      "Music": "Musique",
      "Photos": "Photos",
      "Image Lab": "Labo image",
      "Audio Lab": "Labo audio",
      "Video Lab": "Labo vidéo",
      "Search": "Recherche",
      "Glass Forge": "Forge de verre",
      "About": "À propos",
      "Bug Reporter": "Rapport de bogue",
      "Cancel": "Annuler",
      "OK": "OK",
      "Delete": "Supprimer",
      "Create": "Créer",
      "Got it": "Compris",
      "Save": "Enregistrer",
      "Open": "Ouvrir",
      "Close": "Fermer",
      "Remove": "Retirer",
      "Add": "Ajouter",
      "Apply": "Appliquer",
      "Reset": "Réinitialiser",
      "Done": "Terminé",
      "On": "Activé",
      "Off": "Désactivé",
      "Full": "Complet",
      "Reduced": "Réduit",
      "Small": "Petit",
      "Medium": "Moyen",
      "Large": "Grand",
      "Bottom": "En bas",
      "Left": "Gauche",
      "Right": "Droite",
      "Position": "Position",
      "Size": "Taille",
      "Behaviour": "Comportement",
      "Preview": "Aperçu",
      "Title": "Titre",
      "Severity": "Gravité",
      "Copy": "Copier",
      "Appearance": "Apparence",
      "Glass": "Verre",
      "Desktop": "Bureau",
      "Storage": "Stockage",
      "Wallpaper": "Fond d'écran",
      "Looks": "Styles",
      "Users": "Utilisateurs",
      "Widgets": "Widgets",
      "Shortcuts": "Raccourcis",
      "Lock": "Verrouillage",
      "Zoom": "Zoom",
      "Presets": "Préréglages",
      "Optics": "Optique",
      "Blur": "Flou",
      "Tint": "Teinte",
      "Saturation": "Saturation",
      "Brightness": "Luminosité",
      "Edge thickness": "Épaisseur du bord",
      "Dispersion": "Dispersion",
      "Sheen": "Reflet",
      "Corner radius": "Rayon des coins",
      "Surface finish": "Finition de surface",
      "The light": "La lumière",
      "Refraction": "Réfraction",
      "Motion": "Animation",
      "Reset optics": "Réinitialiser l'optique",
      "Account": "Compte",
      "User name": "Nom d'utilisateur",
      "Windows": "Fenêtres",
      "Dock": "Dock",
      "Icon size": "Taille des icônes",
      "Magnification": "Agrandissement",
      "Auto-hide": "Masquage automatique",
      "Setup": "Configuration",
      "Apps in the dock": "Apps du dock",
      "Bring to front": "Mettre au premier plan",
      "Remove from dock": "Retirer du dock",
      "Customise the dock": "Personnaliser le dock",
      "Add to the dock": "Ajouter au dock",
      "All dock settings": "Tous les réglages du dock",
      "New Folder": "Nouveau dossier",
      "New Note": "Nouvelle note",
      "Import files": "Importer des fichiers",
      "Add widget": "Ajouter un widget",
      "Remove widget": "Retirer le widget",
      "Show in Finder": "Afficher dans le Finder",
      "Wallpaper studio": "Studio de fond d'écran",
      "Applications": "Applications",
      "Files": "Fichiers",
      "Actions": "Actions",
      "Application": "Application",
      "System zoom": "Zoom du système",
      "Window zoom": "Zoom de la fenêtre",
      "Zoom in": "Zoom avant",
      "Zoom out": "Zoom arrière",
      "Actual size": "Taille réelle",
      "Reset zoom": "Réinitialiser le zoom",
      "Interface language": "Langue de l'interface",
      "Region and formats": "Région et formats",
      "24-hour clock": "Horloge 24 heures",
      "First day of the week": "Premier jour de la semaine",
      "Right-to-left layout": "Disposition de droite à gauche",
      "Sunday": "Dimanche",
      "Monday": "Lundi",
      "Automatic": "Automatique",
      "Coverage": "Couverture",
      "Report a bug": "Signaler un bogue",
      "Bug reports": "Rapports de bogues",
      "What happened?": "Que s'est-il passé ?",
      "Steps to reproduce": "Étapes pour reproduire",
      "Include diagnostics": "Inclure les diagnostics",
      "File the report": "Envoyer le rapport",
      "Filed reports": "Rapports envoyés",
      "No reports yet": "Aucun rapport pour l'instant",
      "Copy as Markdown": "Copier en Markdown",
      "Diagnostics": "Diagnostics",
      "Cosmetic": "Cosmétique",
      "Annoying": "Agaçant",
      "Broken": "Cassé",
      "Hide the bug": "Cacher l'insecte",
      "Begin": "Commencer",
      "Continue": "Continuer",
      "Back": "Retour",
      "Skip setup": "Passer la configuration",
      "Who is using this?": "Qui va s’en servir ?",
      "Squash it": "Écrasez-le"
    },

    de: {
      "About This System": "Über dieses System",
      "System Settings": "Systemeinstellungen",
      "Tune the Glass": "Glas abstimmen",
      "Open Terminal": "Terminal öffnen",
      "Close All Windows": "Alle Fenster schließen",
      "Restart": "Neu starten",
      "Language": "Sprache",
      "View": "Ansicht",
      "Help": "Hilfe",
      "Theme": "Thema",
      "Minimise": "Minimieren",
      "Maximise": "Maximieren",
      "Restore": "Wiederherstellen",
      "Close Window": "Fenster schließen",
      "No window open": "Kein Fenster geöffnet",
      "Take the guided tour": "Geführte Tour starten",
      "Show me the glass": "Zeig mir das Glas",
      "Keyboard": "Tastatur",
      "Launcher": "Starter",
      "Cycle windows": "Fenster wechseln",
      "Close window": "Fenster schließen",
      "Minimise window": "Fenster minimieren",
      "Settings": "Einstellungen",
      "Lock the screen": "Bildschirm sperren",
      "Finder": "Finder",
      "Notes": "Notizen",
      "Terminal": "Terminal",
      "Calculator": "Rechner",
      "Clock": "Uhr",
      "Calendar": "Kalender",
      "Focus": "Fokus",
      "Music": "Musik",
      "Photos": "Fotos",
      "Image Lab": "Bildlabor",
      "Audio Lab": "Audiolabor",
      "Video Lab": "Videolabor",
      "Search": "Suche",
      "Glass Forge": "Glasschmiede",
      "About": "Über",
      "Bug Reporter": "Fehlerbericht",
      "Cancel": "Abbrechen",
      "OK": "OK",
      "Delete": "Löschen",
      "Create": "Erstellen",
      "Got it": "Verstanden",
      "Save": "Speichern",
      "Open": "Öffnen",
      "Close": "Schließen",
      "Remove": "Entfernen",
      "Add": "Hinzufügen",
      "Apply": "Anwenden",
      "Reset": "Zurücksetzen",
      "Done": "Fertig",
      "On": "Ein",
      "Off": "Aus",
      "Full": "Voll",
      "Reduced": "Reduziert",
      "Small": "Klein",
      "Medium": "Mittel",
      "Large": "Groß",
      "Bottom": "Unten",
      "Left": "Links",
      "Right": "Rechts",
      "Position": "Position",
      "Size": "Größe",
      "Behaviour": "Verhalten",
      "Preview": "Vorschau",
      "Title": "Titel",
      "Severity": "Schweregrad",
      "Copy": "Kopieren",
      "Appearance": "Erscheinungsbild",
      "Glass": "Glas",
      "Desktop": "Schreibtisch",
      "Storage": "Speicher",
      "Wallpaper": "Hintergrund",
      "Looks": "Looks",
      "Users": "Benutzer",
      "Widgets": "Widgets",
      "Shortcuts": "Kurzbefehle",
      "Lock": "Sperre",
      "Zoom": "Zoom",
      "Presets": "Voreinstellungen",
      "Optics": "Optik",
      "Blur": "Weichzeichnen",
      "Tint": "Tönung",
      "Saturation": "Sättigung",
      "Brightness": "Helligkeit",
      "Edge thickness": "Kantendicke",
      "Dispersion": "Dispersion",
      "Sheen": "Glanz",
      "Corner radius": "Eckenradius",
      "Surface finish": "Oberflächenfinish",
      "The light": "Das Licht",
      "Refraction": "Refraktion",
      "Motion": "Bewegung",
      "Reset optics": "Optik zurücksetzen",
      "Account": "Konto",
      "User name": "Benutzername",
      "Windows": "Fenster",
      "Dock": "Dock",
      "Icon size": "Symbolgröße",
      "Magnification": "Vergrößerung",
      "Auto-hide": "Automatisch ausblenden",
      "Setup": "Einrichtung",
      "Apps in the dock": "Apps im Dock",
      "Bring to front": "In den Vordergrund",
      "Remove from dock": "Aus dem Dock entfernen",
      "Customise the dock": "Dock anpassen",
      "Add to the dock": "Zum Dock hinzufügen",
      "All dock settings": "Alle Dock-Einstellungen",
      "New Folder": "Neuer Ordner",
      "New Note": "Neue Notiz",
      "Import files": "Dateien importieren",
      "Add widget": "Widget hinzufügen",
      "Remove widget": "Widget entfernen",
      "Show in Finder": "Im Finder zeigen",
      "Wallpaper studio": "Hintergrund-Studio",
      "Applications": "Programme",
      "Files": "Dateien",
      "Actions": "Aktionen",
      "Application": "Programm",
      "System zoom": "Systemzoom",
      "Window zoom": "Fensterzoom",
      "Zoom in": "Vergrößern",
      "Zoom out": "Verkleinern",
      "Actual size": "Originalgröße",
      "Reset zoom": "Zoom zurücksetzen",
      "Interface language": "Sprache der Oberfläche",
      "Region and formats": "Region und Formate",
      "24-hour clock": "24-Stunden-Uhr",
      "First day of the week": "Erster Tag der Woche",
      "Right-to-left layout": "Layout von rechts nach links",
      "Sunday": "Sonntag",
      "Monday": "Montag",
      "Automatic": "Automatisch",
      "Coverage": "Abdeckung",
      "Report a bug": "Fehler melden",
      "Bug reports": "Fehlerberichte",
      "What happened?": "Was ist passiert?",
      "Steps to reproduce": "Schritte zum Nachstellen",
      "Include diagnostics": "Diagnose beilegen",
      "File the report": "Bericht einreichen",
      "Filed reports": "Eingereichte Berichte",
      "No reports yet": "Noch keine Berichte",
      "Copy as Markdown": "Als Markdown kopieren",
      "Diagnostics": "Diagnose",
      "Cosmetic": "Kosmetisch",
      "Annoying": "Störend",
      "Broken": "Kaputt",
      "Hide the bug": "Den Käfer verstecken",
      "Begin": "Beginnen",
      "Continue": "Weiter",
      "Back": "Zurück",
      "Skip setup": "Einrichtung überspringen",
      "Who is using this?": "Wer benutzt das hier?",
      "Squash it": "Zerquetsch ihn"
    },

    hi: {
      "About This System": "इस सिस्टम के बारे में",
      "System Settings": "सिस्टम सेटिंग्स",
      "Tune the Glass": "काँच को समायोजित करें",
      "Open Terminal": "टर्मिनल खोलें",
      "Close All Windows": "सभी विंडो बंद करें",
      "Restart": "पुनः आरंभ करें",
      "Language": "भाषा",
      "View": "दृश्य",
      "Help": "सहायता",
      "Theme": "थीम",
      "Minimise": "छोटा करें",
      "Maximise": "बड़ा करें",
      "Restore": "पुनर्स्थापित करें",
      "Close Window": "विंडो बंद करें",
      "No window open": "कोई विंडो खुली नहीं है",
      "Take the guided tour": "निर्देशित भ्रमण लें",
      "Show me the glass": "मुझे काँच दिखाओ",
      "Keyboard": "कीबोर्ड",
      "Launcher": "लॉन्चर",
      "Cycle windows": "विंडो बदलें",
      "Close window": "विंडो बंद करें",
      "Minimise window": "विंडो छोटी करें",
      "Settings": "सेटिंग्स",
      "Lock the screen": "स्क्रीन लॉक करें",
      "Finder": "फ़ाइंडर",
      "Notes": "नोट्स",
      "Terminal": "टर्मिनल",
      "Calculator": "कैलकुलेटर",
      "Clock": "घड़ी",
      "Calendar": "कैलेंडर",
      "Focus": "फ़ोकस",
      "Music": "संगीत",
      "Photos": "तस्वीरें",
      "Image Lab": "इमेज लैब",
      "Audio Lab": "ऑडियो लैब",
      "Video Lab": "वीडियो लैब",
      "Search": "खोज",
      "Glass Forge": "काँच की भट्टी",
      "About": "परिचय",
      "Bug Reporter": "बग रिपोर्टर",
      "Cancel": "रद्द करें",
      "OK": "ठीक है",
      "Delete": "हटाएँ",
      "Create": "बनाएँ",
      "Got it": "समझ गया",
      "Save": "सहेजें",
      "Open": "खोलें",
      "Close": "बंद करें",
      "Remove": "निकालें",
      "Add": "जोड़ें",
      "Apply": "लागू करें",
      "Reset": "रीसेट करें",
      "Done": "पूर्ण",
      "On": "चालू",
      "Off": "बंद",
      "Full": "पूरा",
      "Reduced": "कम",
      "Small": "छोटा",
      "Medium": "मध्यम",
      "Large": "बड़ा",
      "Bottom": "नीचे",
      "Left": "बाएँ",
      "Right": "दाएँ",
      "Position": "स्थिति",
      "Size": "आकार",
      "Behaviour": "व्यवहार",
      "Preview": "पूर्वावलोकन",
      "Title": "शीर्षक",
      "Severity": "गंभीरता",
      "Copy": "कॉपी करें",
      "Appearance": "रूप",
      "Glass": "काँच",
      "Desktop": "डेस्कटॉप",
      "Storage": "भंडारण",
      "Wallpaper": "वॉलपेपर",
      "Looks": "लुक्स",
      "Users": "उपयोगकर्ता",
      "Widgets": "विजेट",
      "Shortcuts": "शॉर्टकट",
      "Lock": "लॉक",
      "Zoom": "ज़ूम",
      "Presets": "प्रीसेट",
      "Optics": "प्रकाशिकी",
      "Blur": "धुंधलापन",
      "Tint": "रंगत",
      "Saturation": "संतृप्ति",
      "Brightness": "चमक",
      "Edge thickness": "किनारे की मोटाई",
      "Dispersion": "प्रकीर्णन",
      "Sheen": "चमकाव",
      "Corner radius": "कोने की त्रिज्या",
      "Surface finish": "सतह की फिनिश",
      "The light": "प्रकाश",
      "Refraction": "अपवर्तन",
      "Motion": "गति",
      "Reset optics": "प्रकाशिकी रीसेट करें",
      "Account": "खाता",
      "User name": "उपयोगकर्ता नाम",
      "Windows": "विंडो",
      "Dock": "डॉक",
      "Icon size": "आइकन आकार",
      "Magnification": "आवर्धन",
      "Auto-hide": "स्वतः छिपाएँ",
      "Setup": "सेटअप",
      "Apps in the dock": "डॉक में ऐप्स",
      "Bring to front": "सामने लाएँ",
      "Remove from dock": "डॉक से निकालें",
      "Customise the dock": "डॉक अनुकूलित करें",
      "Add to the dock": "डॉक में जोड़ें",
      "All dock settings": "सभी डॉक सेटिंग्स",
      "New Folder": "नया फ़ोल्डर",
      "New Note": "नया नोट",
      "Import files": "फ़ाइलें आयात करें",
      "Add widget": "विजेट जोड़ें",
      "Remove widget": "विजेट निकालें",
      "Show in Finder": "फ़ाइंडर में दिखाएँ",
      "Wallpaper studio": "वॉलपेपर स्टूडियो",
      "Applications": "अनुप्रयोग",
      "Files": "फ़ाइलें",
      "Actions": "क्रियाएँ",
      "Application": "अनुप्रयोग",
      "System zoom": "सिस्टम ज़ूम",
      "Window zoom": "विंडो ज़ूम",
      "Zoom in": "ज़ूम इन",
      "Zoom out": "ज़ूम आउट",
      "Actual size": "वास्तविक आकार",
      "Reset zoom": "ज़ूम रीसेट करें",
      "Interface language": "इंटरफ़ेस की भाषा",
      "Region and formats": "क्षेत्र और प्रारूप",
      "24-hour clock": "24-घंटे की घड़ी",
      "First day of the week": "सप्ताह का पहला दिन",
      "Right-to-left layout": "दाएँ से बाएँ लेआउट",
      "Sunday": "रविवार",
      "Monday": "सोमवार",
      "Automatic": "स्वचालित",
      "Coverage": "कवरेज",
      "Report a bug": "बग की रिपोर्ट करें",
      "Bug reports": "बग रिपोर्टें",
      "What happened?": "क्या हुआ?",
      "Steps to reproduce": "दोहराने के चरण",
      "Include diagnostics": "निदान शामिल करें",
      "File the report": "रिपोर्ट भेजें",
      "Filed reports": "भेजी गई रिपोर्टें",
      "No reports yet": "अभी कोई रिपोर्ट नहीं",
      "Copy as Markdown": "Markdown के रूप में कॉपी करें",
      "Diagnostics": "निदान",
      "Cosmetic": "बनावटी",
      "Annoying": "परेशान करने वाला",
      "Broken": "टूटा हुआ",
      "Hide the bug": "कीड़े को छिपाएँ",
      "Begin": "शुरू करें",
      "Continue": "आगे बढ़ें",
      "Back": "पीछे",
      "Skip setup": "सेटअप छोड़ें",
      "Who is using this?": "इसे कौन उपयोग कर रहा है?",
      "Squash it": "इसे कुचल दो"
    },

    ja: {
      "About This System": "このシステムについて",
      "System Settings": "システム設定",
      "Tune the Glass": "ガラスを調整",
      "Open Terminal": "ターミナルを開く",
      "Close All Windows": "すべてのウインドウを閉じる",
      "Restart": "再起動",
      "Language": "言語",
      "View": "表示",
      "Help": "ヘルプ",
      "Theme": "テーマ",
      "Minimise": "最小化",
      "Maximise": "最大化",
      "Restore": "元のサイズに戻す",
      "Close Window": "ウインドウを閉じる",
      "No window open": "開いているウインドウはありません",
      "Take the guided tour": "ガイドツアーを見る",
      "Show me the glass": "ガラスを見せて",
      "Keyboard": "キーボード",
      "Launcher": "ランチャー",
      "Cycle windows": "ウインドウを切り替える",
      "Close window": "ウインドウを閉じる",
      "Minimise window": "ウインドウを最小化",
      "Settings": "設定",
      "Lock the screen": "画面をロック",
      "Finder": "ファインダー",
      "Notes": "メモ",
      "Terminal": "ターミナル",
      "Calculator": "電卓",
      "Clock": "時計",
      "Calendar": "カレンダー",
      "Focus": "フォーカス",
      "Music": "ミュージック",
      "Photos": "写真",
      "Image Lab": "イメージラボ",
      "Audio Lab": "オーディオラボ",
      "Video Lab": "ビデオラボ",
      "Search": "検索",
      "Glass Forge": "ガラス工房",
      "About": "情報",
      "Bug Reporter": "バグ報告",
      "Cancel": "キャンセル",
      "OK": "OK",
      "Delete": "削除",
      "Create": "作成",
      "Got it": "了解",
      "Save": "保存",
      "Open": "開く",
      "Close": "閉じる",
      "Remove": "取り除く",
      "Add": "追加",
      "Apply": "適用",
      "Reset": "リセット",
      "Done": "完了",
      "On": "オン",
      "Off": "オフ",
      "Full": "フル",
      "Reduced": "控えめ",
      "Small": "小",
      "Medium": "中",
      "Large": "大",
      "Bottom": "下",
      "Left": "左",
      "Right": "右",
      "Position": "位置",
      "Size": "サイズ",
      "Behaviour": "動作",
      "Preview": "プレビュー",
      "Title": "タイトル",
      "Severity": "深刻度",
      "Copy": "コピー",
      "Appearance": "外観",
      "Glass": "ガラス",
      "Desktop": "デスクトップ",
      "Storage": "ストレージ",
      "Wallpaper": "壁紙",
      "Looks": "ルック",
      "Users": "ユーザ",
      "Widgets": "ウィジェット",
      "Shortcuts": "ショートカット",
      "Lock": "ロック",
      "Zoom": "ズーム",
      "Presets": "プリセット",
      "Optics": "光学",
      "Blur": "ぼかし",
      "Tint": "色味",
      "Saturation": "彩度",
      "Brightness": "明るさ",
      "Edge thickness": "縁の厚み",
      "Dispersion": "分散",
      "Sheen": "光沢",
      "Corner radius": "角の丸み",
      "Surface finish": "表面の仕上げ",
      "The light": "光",
      "Refraction": "屈折",
      "Motion": "モーション",
      "Reset optics": "光学をリセット",
      "Account": "アカウント",
      "User name": "ユーザ名",
      "Windows": "ウインドウ",
      "Dock": "Dock",
      "Icon size": "アイコンサイズ",
      "Magnification": "拡大効果",
      "Auto-hide": "自動的に隠す",
      "Setup": "セットアップ",
      "Apps in the dock": "Dock のアプリ",
      "Bring to front": "最前面に移動",
      "Remove from dock": "Dock から削除",
      "Customise the dock": "Dock をカスタマイズ",
      "Add to the dock": "Dock に追加",
      "All dock settings": "すべての Dock 設定",
      "New Folder": "新規フォルダ",
      "New Note": "新規メモ",
      "Import files": "ファイルを読み込む",
      "Add widget": "ウィジェットを追加",
      "Remove widget": "ウィジェットを削除",
      "Show in Finder": "ファインダーで表示",
      "Wallpaper studio": "壁紙スタジオ",
      "Applications": "アプリケーション",
      "Files": "ファイル",
      "Actions": "アクション",
      "Application": "アプリケーション",
      "System zoom": "システムのズーム",
      "Window zoom": "ウインドウのズーム",
      "Zoom in": "ズームイン",
      "Zoom out": "ズームアウト",
      "Actual size": "実際のサイズ",
      "Reset zoom": "ズームをリセット",
      "Interface language": "インターフェースの言語",
      "Region and formats": "地域と書式",
      "24-hour clock": "24 時間表示",
      "First day of the week": "週の始まり",
      "Right-to-left layout": "右から左のレイアウト",
      "Sunday": "日曜日",
      "Monday": "月曜日",
      "Automatic": "自動",
      "Coverage": "カバー率",
      "Report a bug": "バグを報告",
      "Bug reports": "バグ報告",
      "What happened?": "何が起きましたか？",
      "Steps to reproduce": "再現手順",
      "Include diagnostics": "診断情報を含める",
      "File the report": "報告を送る",
      "Filed reports": "送信した報告",
      "No reports yet": "まだ報告はありません",
      "Copy as Markdown": "Markdown としてコピー",
      "Diagnostics": "診断情報",
      "Cosmetic": "見た目だけ",
      "Annoying": "わずらわしい",
      "Broken": "壊れている",
      "Hide the bug": "虫を隠す",
      "Begin": "はじめる",
      "Continue": "続ける",
      "Back": "戻る",
      "Skip setup": "セットアップをスキップ",
      "Who is using this?": "使うのはどなたですか？",
      "Squash it": "つぶす"
    },

    ar: {
      "About This System": "حول هذا النظام",
      "System Settings": "إعدادات النظام",
      "Tune the Glass": "ضبط الزجاج",
      "Open Terminal": "فتح الطرفية",
      "Close All Windows": "إغلاق كل النوافذ",
      "Restart": "إعادة التشغيل",
      "Language": "اللغة",
      "View": "عرض",
      "Help": "مساعدة",
      "Theme": "السمة",
      "Minimise": "تصغير",
      "Maximise": "تكبير",
      "Restore": "استعادة",
      "Close Window": "إغلاق النافذة",
      "No window open": "لا توجد نافذة مفتوحة",
      "Take the guided tour": "خذ الجولة الموجهة",
      "Show me the glass": "أرني الزجاج",
      "Keyboard": "لوحة المفاتيح",
      "Launcher": "المشغّل",
      "Cycle windows": "التبديل بين النوافذ",
      "Close window": "إغلاق النافذة",
      "Minimise window": "تصغير النافذة",
      "Settings": "الإعدادات",
      "Lock the screen": "قفل الشاشة",
      "Finder": "الباحث",
      "Notes": "الملاحظات",
      "Terminal": "الطرفية",
      "Calculator": "الآلة الحاسبة",
      "Clock": "الساعة",
      "Calendar": "التقويم",
      "Focus": "التركيز",
      "Music": "الموسيقى",
      "Photos": "الصور",
      "Image Lab": "مختبر الصور",
      "Audio Lab": "مختبر الصوت",
      "Video Lab": "مختبر الفيديو",
      "Search": "البحث",
      "Glass Forge": "مسبك الزجاج",
      "About": "حول",
      "Bug Reporter": "مُبلِّغ الأخطاء",
      "Cancel": "إلغاء",
      "OK": "موافق",
      "Delete": "حذف",
      "Create": "إنشاء",
      "Got it": "فهمت",
      "Save": "حفظ",
      "Open": "فتح",
      "Close": "إغلاق",
      "Remove": "إزالة",
      "Add": "إضافة",
      "Apply": "تطبيق",
      "Reset": "إعادة التعيين",
      "Done": "تم",
      "On": "تشغيل",
      "Off": "إيقاف",
      "Full": "كامل",
      "Reduced": "مخفَّف",
      "Small": "صغير",
      "Medium": "متوسط",
      "Large": "كبير",
      "Bottom": "أسفل",
      "Left": "يسار",
      "Right": "يمين",
      "Position": "الموضع",
      "Size": "الحجم",
      "Behaviour": "السلوك",
      "Preview": "معاينة",
      "Title": "العنوان",
      "Severity": "الخطورة",
      "Copy": "نسخ",
      "Appearance": "المظهر",
      "Glass": "الزجاج",
      "Desktop": "سطح المكتب",
      "Storage": "التخزين",
      "Wallpaper": "الخلفية",
      "Looks": "الأنماط",
      "Users": "المستخدمون",
      "Widgets": "الأدوات",
      "Shortcuts": "الاختصارات",
      "Lock": "القفل",
      "Zoom": "التكبير",
      "Presets": "الإعدادات الجاهزة",
      "Optics": "البصريات",
      "Blur": "التمويه",
      "Tint": "الصباغة",
      "Saturation": "التشبع",
      "Brightness": "السطوع",
      "Edge thickness": "سماكة الحافة",
      "Dispersion": "التشتت",
      "Sheen": "اللمعان",
      "Corner radius": "نصف قطر الزوايا",
      "Surface finish": "تشطيب السطح",
      "The light": "الضوء",
      "Refraction": "الانكسار",
      "Motion": "الحركة",
      "Reset optics": "إعادة تعيين البصريات",
      "Account": "الحساب",
      "User name": "اسم المستخدم",
      "Windows": "النوافذ",
      "Dock": "الشريط",
      "Icon size": "حجم الأيقونات",
      "Magnification": "التضخيم",
      "Auto-hide": "الإخفاء التلقائي",
      "Setup": "الإعداد",
      "Apps in the dock": "التطبيقات في الشريط",
      "Bring to front": "إحضار إلى الأمام",
      "Remove from dock": "إزالة من الشريط",
      "Customise the dock": "تخصيص الشريط",
      "Add to the dock": "إضافة إلى الشريط",
      "All dock settings": "كل إعدادات الشريط",
      "New Folder": "مجلد جديد",
      "New Note": "ملاحظة جديدة",
      "Import files": "استيراد ملفات",
      "Add widget": "إضافة أداة",
      "Remove widget": "إزالة الأداة",
      "Show in Finder": "إظهار في الباحث",
      "Wallpaper studio": "استوديو الخلفيات",
      "Applications": "التطبيقات",
      "Files": "الملفات",
      "Actions": "الإجراءات",
      "Application": "تطبيق",
      "System zoom": "تكبير النظام",
      "Window zoom": "تكبير النافذة",
      "Zoom in": "تكبير",
      "Zoom out": "تصغير",
      "Actual size": "الحجم الفعلي",
      "Reset zoom": "إعادة تعيين التكبير",
      "Interface language": "لغة الواجهة",
      "Region and formats": "المنطقة والتنسيقات",
      "24-hour clock": "نظام 24 ساعة",
      "First day of the week": "أول يوم في الأسبوع",
      "Right-to-left layout": "تخطيط من اليمين إلى اليسار",
      "Sunday": "الأحد",
      "Monday": "الاثنين",
      "Automatic": "تلقائي",
      "Coverage": "التغطية",
      "Report a bug": "الإبلاغ عن خطأ",
      "Bug reports": "تقارير الأخطاء",
      "What happened?": "ماذا حدث؟",
      "Steps to reproduce": "خطوات إعادة الإنتاج",
      "Include diagnostics": "تضمين التشخيصات",
      "File the report": "إرسال التقرير",
      "Filed reports": "التقارير المرسلة",
      "No reports yet": "لا توجد تقارير بعد",
      "Copy as Markdown": "نسخ بصيغة Markdown",
      "Diagnostics": "التشخيصات",
      "Cosmetic": "شكلي",
      "Annoying": "مزعج",
      "Broken": "معطّل",
      "Hide the bug": "إخفاء الحشرة",
      "Begin": "ابدأ",
      "Continue": "متابعة",
      "Back": "رجوع",
      "Skip setup": "تخطي الإعداد",
      "Who is using this?": "من الذي سيستخدمه؟",
      "Squash it": "اسحقها"
    }
  };
})(window.DS);
